name: orderly
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.3
  dio: ^5.9.0
  flutter_secure_storage: ^10.0.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/orderly_logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/orderly_logo.png"
  min_sdk_android: 21
